//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoaHoc()
        {
            this.GiaoDichHocPhi = new HashSet<GiaoDichHocPhi>();
            this.LopHoc = new HashSet<LopHoc>();
            this.NguoiQuanLy = new HashSet<NguoiQuanLy>();
            this.TaiLieuHocTap = new HashSet<TaiLieuHocTap>();
            this.BinhLuanKhoaHoc = new HashSet<BinhLuanKhoaHoc>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string MaChuongTrinh { get; set; }
        public double HocPhi { get; set; }
        public string LoaiKH { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual ChuongTrinhHoc ChuongTrinhHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichHocPhi> GiaoDichHocPhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiQuanLy> NguoiQuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieuHocTap> TaiLieuHocTap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanKhoaHoc> BinhLuanKhoaHoc { get; set; }
    }
}
