//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public string MaLienHe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime Ngaylienhe { get; set; }
        public string MaHV { get; set; }
        public string MaGV { get; set; }
        public string MaQL { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocVien HocVien { get; set; }
        public virtual NguoiQuanLy NguoiQuanLy { get; set; }
    }
}
