//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [Key]
        public int MaTK { get; set; }
        [Display(Name = "Nhập tên đăng nhập")]
        [Required(ErrorMessage = "Bạn phải nhập tên đăng nhập")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Nhập tên mật khẩu")]
        [Required(ErrorMessage = "Bạn phải nhập mật khẩu")]
        public string MatKhau { get; set; }
        public string QuyenHan { get; set; }
        [Display(Name = "Nhập mã học viên")]
        [Required(ErrorMessage = "Bạn phải nhập mã học viên")]
        public string MaHV { get; set; }
        public string MaGV { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocVien HocVien { get; set; }
    }
}
